exports.COL_ID = 'id'
exports.COL_CODE = 'code'
exports.COL_NAME = 'name'
exports.COL_PARTNER_NAME = 'partner_name'
exports.COL_FULL_NAME = 'full_name'
exports.COL_DATE = 'date'
exports.COL_ADDRESS = 'address'
exports.COL_HAS_READ = 'has_read'
exports.COL_READ = 'read'
exports.COL_DATE_TIME = 'date_time'
exports.COL_FROM_DATE = 'from_date'
exports.COL_IS_ACTIVE = 'is_active'
exports.COL_IS_DEFAULT = 'is_default'
exports.COL_TO_DATE = 'to_date'
exports.COL_NUMBER_ID = 'number_id'
exports.COL_PARENT_ID = 'parent_id'
exports.COL_DESCRIPTION = 'description'
exports.COL_CREATED_AT = 'created_at'
exports.COL_CREATED_BY = 'created_by'
exports.COL_UPDATED_AT = 'updated_at'
exports.COL_UPDATED_BY = 'updated_by'
// user
exports.COL_USER_ID = 'user_id'
exports.COL_USERNAME = 'username'
exports.COL_FIRST_NAME = 'first_name'
exports.COL_LAST_NAME = 'last_name'
exports.COL_EMAIL = 'email'
exports.COL_PASSWORD = 'password'
// token
exports.COL_TOKEN_ID = 'token_id'
exports.COL_TOKEN = 'token'
exports.COL_TYPE = 'type'
exports.COL_IS_REVOKED = 'is_revoked'
// account
exports.COL_ACCOUNT_ID = 'account_id'
exports.COL_ACCOUNT_TYPE = 'account_type'

// media
exports.COL_MEDIA_ID = 'media_id'
exports.COL_FILE_NAME = 'file_name'
exports.COL_CONTENT_TYPE = 'content_type'

// profile
exports.COL_PROFILE_ID = 'profile_id'
exports.COL_BOY_FIRST_NAME = 'boy_first_name'
exports.COL_BOY_LAST_NAME = 'boy_last_name'
exports.COL_GIRL_FIRST_NAME = 'girl_first_name'
exports.COL_GIRL_LAST_NAME = 'girl_last_name'
exports.COL_BOY_FATHER_NAME = 'boy_father_name'
exports.COL_BOY_MOTHER_NAME = 'boy_mother_name'
exports.COL_GIRL_FATHER_NAME = 'girl_father_name'
exports.COL_GIRL_MOTHER_NAME = 'girl_mother_name'
exports.COL_WEDDING_ADDRESS = 'wedding_address'
exports.COL_RECEPTION_DATE = 'reception_date'
exports.COL_MARRIAGE_CONTRACT_DATE = 'marriage_contract_date'
